### ISSUE TITLE
French translation done !

### ISSUE THREAD

**Issue by KLFD9** [poLLi/SB_Tools_Localization#6]
Hi, first of all, thank you for this wonderful tool that you shared with us. 
I am in charge of transcribing the information about Starbase for the French community. 
I took the liberty after to create an article about your software on https://www.starbasefrance.fr , to translate it for the French speaking community. 
I have submitted the translation file to you. 
I look forward to talking to you again. 

Kiki Lefada [KLFD]
![Logo](https://user-images.githubusercontent.com/26156607/130368903-ab6cd0a3-fdf0-4600-846d-d6ecfc531b3c.png)

**Comment by poLLi** [comment]
thank you :)

Added it in and deploy in just a second
